In [1321]:
import numpy as np
print("NumPy is ready!")

NumPy is ready!


In [1322]:
import numpy as np

print(f"NumPy Version: {np.__version__}")

np.show_config()

NumPy Version: 2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Malahma/anaconda3/Library/include
    lib directory: C:/Users/Malahma/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Malahma/anaconda3/Library/include
    lib directory: C:/Users/Malahma/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cytho

In [1323]:
#create a null vector of size 10
import numpy as np
null_vector=np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [1324]:
#How to find the memory size of any array
import numpy as np
array1 = np.array([1, 7, 13, 105])
print(array1)
array1.itemsize
array1.size*array1.itemsize


[  1   7  13 105]


32

In [1325]:
#5 How to get the documentation of the numpy add function?
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [1326]:
#6 Create a null vector of size 10 but the fifth value which is 1
import numpy as np

Z = np.zeros(10)
Z[4] = 1

print(Z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [1327]:
#7 Create a vector with values ranging from 10 to 49
import numpy as np

arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [1328]:
#8 Reverse a vector (first element becomes last)
import numpy as np

arr=np.arange(1,10)
arr_reversed=arr[::-1]
print(f"array {arr}")
print(f"reversed array {arr_reversed}")


array [1 2 3 4 5 6 7 8 9]
reversed array [9 8 7 6 5 4 3 2 1]


In [1329]:
#9 Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
matrix=np.arange(0,9).reshape((3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [1330]:
#10 Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)[0]

print(f"Indices: {indices}")

Indices: [0 1 4]


In [1331]:
#11 Create a 3x3 identity matrix 
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [1332]:
#12 Create a 3x3x3 array with random values
import numpy as np

array = np.random.random((3, 3, 3))
print(np.round(array, 2))

[[[0.88 0.82 0.92]
  [0.69 0.18 0.5 ]
  [0.33 0.67 0.49]]

 [[0.06 0.82 0.41]
  [0.46 0.08 0.44]
  [0.57 0.63 0.06]]

 [[0.35 0.76 0.33]
  [0.16 0.12 0.98]
  [0.85 0.82 0.45]]]


In [1333]:
import numpy as np 

arr = np.random.randint(100, size=(10, 10))
print(arr)
print(np.min(arr))
print(np.max(arr))

[[ 1 99  2 81 90 28  7 79 41  0]
 [82 58 87 69 69 33  5  1 38 30]
 [59 47 58 48 15 11 15 32 64 53]
 [86  0 70 54 81 89 27 98 61 39]
 [41 51 79 30 82 80 18 29 60 63]
 [ 2 22 48 37 94  3 21  3 53 99]
 [58 59  5 75 17 51 58 27 68 24]
 [58  4 40 47 84 52  0  0 60 35]
 [51 65 75 74 46 65 31  7 35 70]
 [97 77 47 87 43 56  5 15 11 62]]
0
99


In [1334]:
#14 Create a random vector of size 30 and find the mean value
Z = np.random.random(30)
m = Z.mean()

print(m)


0.45937613356114987


In [1335]:
#15 Create a 2d array with 1 on the border and 0 inside 
n=np.ones((5,5))
print(n)
n[1:-1,1:-1]=0
print(n)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [1336]:
#16 How to add a border (filled with 0's) around an existing array?
Z = np.ones((3,3))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [1337]:
#17 What is the result of the following expression?

print(0 * np.nan)             # Result: nan
print(np.nan == np.nan)       # Result: False
print(np.inf > np.nan)        # Result: False
print(np.nan - np.nan)        # Result: nan
print(np.nan in set([np.nan]))# Result: True
print(0.3 == 3 * 0.1)         # Result: False

nan
False
False
nan
True
False


In [1338]:
#18 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Z = np.diag(1 + np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [1339]:
#19 Create an 8x8 matrix and fill it with a checkerboard pattern
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [1340]:
#20 Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element

res = np.unravel_index(100, (6,7,8))
result = tuple(int(i) for i in res)
print(result)

(1, 5, 4)


In [1341]:
#21 Create a checkerboard 8x8 matrix using the tile function
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [1342]:
#22 Normalize a 5x5 random matrix
Z = np.random.random((5,5))
Z = (Z - Z.min()) / (Z.max() - Z.min())
Z_int = (Z * 10).astype(int)

print(Z_int)

[[ 7  5  4  5  3]
 [ 9  3  0  3  7]
 [ 2  9  1  0  0]
 [ 9  5  3  0 10]
 [ 3  3  5  4  6]]


In [1343]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color_layout = [
    ("r", np.uint8),
    ("g", np.uint8), 
    ("b", np.uint8), 
    ("a", np.uint8) 
]

color = np.dtype(color_layout)

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [1344]:
 #24 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
import numpy as np
A = np.ones((5, 3))
B = np.ones((3, 2))
Z = (A @ B).astype(int)

print(Z)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


In [1345]:
#25 Given a 1D array, negate all elements which are between 3 and 8, in place.
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1

print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [1346]:
# 26. What is the output of the following script?
# The first sum is Python's built-in sum (starts at -1)
print(sum(range(5), -1)) 

# This overwrites the built-in sum function
from numpy import *
print(sum(range(5), -1))

10
10


In [1347]:
# 27. Consider an integer vector Z, which of these expressions are legal?
import numpy as np
Z = np.arange(3)

print(Z**Z)       
print(2 << Z >> 2) 
print(Z <- Z)    
print(1j*Z)      
print(Z/1/1)      


[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


In [1348]:

np.seterr(all='warn')


with np.errstate(divide='ignore', invalid='ignore'):
    print("1:", np.array(0) / np.array(0))


try:
    print("2:", np.array(0) // np.array(0))
except ZeroDivisionError:
    print("2: Cannot floor divide by zero")

print("3:", np.array([np.nan]).astype(int).astype(float))

1: nan
2: 0
3: [-9.22337204e+18]


C:\Users\Malahma\AppData\Local\Temp\ipykernel_3660\2312204542.py:9: RuntimeWarning: divide by zero encountered in floor_divide
  print("2:", np.array(0) // np.array(0))
C:\Users\Malahma\AppData\Local\Temp\ipykernel_3660\2312204542.py:13: RuntimeWarning: invalid value encountered in cast
  print("3:", np.array([np.nan]).astype(int).astype(float))


In [1349]:
# 28. What are the results of the following expressions?
print("1:", np.array(0) / np.array(0))
print("2:", np.array(0) // np.array(0))
print("3:", np.array([np.nan]).astype(int).astype(float))

1: nan
2: 0
3: [-9.22337204e+18]


C:\Users\Malahma\AppData\Local\Temp\ipykernel_3660\1908351598.py:2: RuntimeWarning: invalid value encountered in divide
  print("1:", np.array(0) / np.array(0))
C:\Users\Malahma\AppData\Local\Temp\ipykernel_3660\1908351598.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print("2:", np.array(0) // np.array(0))
C:\Users\Malahma\AppData\Local\Temp\ipykernel_3660\1908351598.py:4: RuntimeWarning: invalid value encountered in cast
  print("3:", np.array([np.nan]).astype(int).astype(float))


In [1350]:
#29 How to round away from zero a float array 
array = np.random.uniform(-10, 10, 10)
result = np.copysign(np.ceil(np.abs(array)), array)

print(array)
print(result)

[ 5.73523877 -2.32804947  7.81525883  2.69381497  7.73883944  5.63072648
  2.20329554 -3.50493548 -3.53773026  0.82199898]
[ 6. -3.  8.  3.  8.  6.  3. -4. -4.  1.]


In [1351]:
#30 How to find common values between two arrays? 

Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

common_values = np.intersect1d(Z1, Z2)

print(f"Array 1: {Z1}")
print(f"Array 2: {Z2}")
print(f"Common:  {common_values}")

Array 1: [0 3 9 6 7 4 6 2 8 5]
Array 2: [1 3 3 1 1 8 4 6 7 8]
Common:  [3 4 6 7 8]


In [1352]:
#31 ow to ignore all numpy warnings (not recommended)?
old = np.seterr(all='ignore')
Z = np.ones(1) / 0
np.seterr(**old)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [1353]:
import numpy as np

# #32. Is the following expression True? (★☆☆)
# np.sqrt(-1) == np.emath.sqrt(-1)

# We wrap it in a print so you see the result in the console
print("Result of np.sqrt(-1):", np.sqrt(-1))
print("Result of np.emath.sqrt(-1):", np.emath.sqrt(-1))

# This is the actual answer to the question:
comparison = np.sqrt(-1) == np.emath.sqrt(-1)
print("Is the expression True?", comparison)

Result of np.sqrt(-1): nan
Result of np.emath.sqrt(-1): 1j
Is the expression True? False


C:\Users\Malahma\AppData\Local\Temp\ipykernel_3660\1519677791.py:7: RuntimeWarning: invalid value encountered in sqrt
  print("Result of np.sqrt(-1):", np.sqrt(-1))
C:\Users\Malahma\AppData\Local\Temp\ipykernel_3660\1519677791.py:11: RuntimeWarning: invalid value encountered in sqrt
  comparison = np.sqrt(-1) == np.emath.sqrt(-1)


In [1354]:
#33 How to get the dates of yesterday, today and tomorrow?

today     = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow  = today + np.timedelta64(1, 'D')

print("Yesterday: ", yesterday)
print("Today:     ", today)
print("Tomorrow:  ", tomorrow)

Yesterday:  2026-04-03
Today:      2026-04-04
Tomorrow:   2026-04-05


In [1355]:
#34. How to get all the dates corresponding to the month of July 2016?
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [1356]:
#35 35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3) * 1
B = np.ones(3) * 2

np.add(A, B, out=B)

np.divide(A, -2, out=A)

np.multiply(A, B, out=A)

print(A)

[-1.5 -1.5 -1.5]


In [1357]:

Z = np.random.uniform(0, 10, 5)
print("Original Array:", Z)

print("Method 1 (astype):", Z.astype(int))

print("Method 2 (trunc): ", np.trunc(Z))

print("Method 3 (floor): ", np.floor(Z))

print("Method 4 (modulo):", Z - Z % 1)

Original Array: [3.73917918 6.29138423 8.05202123 3.96354633 9.06371423]
Method 1 (astype): [3 6 8 3 9]
Method 2 (trunc):  [3. 6. 8. 3. 9.]
Method 3 (floor):  [3. 6. 8. 3. 9.]
Method 4 (modulo): [3. 6. 8. 3. 9.]


In [1358]:
#37 Create a 5x5 matrix with row values ranging from 0 to 4

matrix = np.zeros((5,5))
matrix += np.arange(5)

print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [1359]:
#38  Consider a generator function that generates 10 integers and use it to build an array 
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(), dtype=float, count=-1)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [1360]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
Z = np.linspace(0, 1, 12, endpoint=True)[1:-1]

print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [1361]:
#40 Create a random vector of size 10 and sort it
Z = np.random.random(10)

Z.sort()

print(Z)

[0.01302739 0.21865908 0.44004628 0.51744133 0.52106663 0.54247304
 0.54828897 0.58888528 0.77002759 0.91189332]


In [1362]:
#41  How to sum a small array faster than np.sum? 

Z = np.random.randint(0, 10, 10) 


total = np.add.reduce(Z)

print(f"Array: {Z}")
print(f"Fast Sum: {total}")

Array: [8 2 1 8 2 7 7 0 0 6]
Fast Sum: 41


In [ ]:
#42 Consider two random arrays A and B, check if they are equal
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)


equal = np.array_equal(A, B)

almost_equal = np.allclose(A, B)

print(f"A: {A}")
print(f"B: {B}")
print(f"Are they exactly equal? {equal}")

A: [1 0 0 1 1]
B: [1 1 0 1 1]
Are they exactly equal? False


In [ ]:
#43 