In [46]:
import numpy as np
print("NumPy is ready!")

NumPy is ready!


In [47]:
import numpy as np

print(f"NumPy Version: {np.__version__}")

np.show_config()

NumPy Version: 2.4.4
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35225",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.4",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35225",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.31.188.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ucojyb64/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/i

c:\Users\Malahma\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [48]:
#create a null vector of size 10
import numpy as np
null_vector=np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
#How to find the memory size of any array
import numpy as np
array1 = np.array([1, 7, 13, 105])
print(array1)
array1.itemsize
array1.size*array1.itemsize


[  1   7  13 105]


32

In [50]:
#5 How to get the documentation of the numpy add function?
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [51]:
#6 Create a null vector of size 10 but the fifth value which is 1
import numpy as np

Z = np.zeros(10)
Z[4] = 1

print(Z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [52]:
#7 Create a vector with values ranging from 10 to 49
import numpy as np

arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [53]:
#8 Reverse a vector (first element becomes last)
import numpy as np

arr=np.arange(1,10)
arr_reversed=arr[::-1]
print(f"array {arr}")
print(f"reversed array {arr_reversed}")


array [1 2 3 4 5 6 7 8 9]
reversed array [9 8 7 6 5 4 3 2 1]


In [54]:
#9 Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
matrix=np.arange(0,9).reshape((3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [55]:
#10 Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)[0]

print(f"Indices: {indices}")

Indices: [0 1 4]


In [56]:
#11 Create a 3x3 identity matrix 
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
#12 Create a 3x3x3 array with random values
import numpy as np

array = np.random.random((3, 3, 3))
print(np.round(array, 2))

[[[0.75 0.19 0.99]
  [0.94 0.58 0.56]
  [0.58 0.82 0.54]]

 [[0.83 0.95 0.67]
  [0.79 0.98 0.98]
  [0.96 0.93 0.53]]

 [[0.54 0.63 0.14]
  [0.39 0.79 0.83]
  [0.71 0.85 0.27]]]


In [58]:
import numpy as np 

arr = np.random.randint(100, size=(10, 10))
print(arr)
print(np.min(arr))
print(np.max(arr))

[[90 19 47 28  0 54 54  7 44 13]
 [96 83 89 81 41 84 32 56 20 24]
 [84 49 55 98 56 75 48 84 51 62]
 [32 44 29 86 64 95 41 30 57 81]
 [18 16 18 71 81  3  9 27 37 84]
 [35 81 94 83 34 28 45 52 21 68]
 [29 49 62 61 83 92 74 64 37 55]
 [61 21 53 76 16 66 35  1 26  4]
 [33 84 83 35 55 80 35 97 66 90]
 [84 25 75  5 32 12  4 82 80 37]]
0
98


In [59]:
#14 Create a random vector of size 30 and find the mean value
Z = np.random.random(30)
m = Z.mean()

print(m)


0.5152123921207172


In [60]:
#15 Create a 2d array with 1 on the border and 0 inside 
n=np.ones((5,5))
print(n)
n[1:-1,1:-1]=0
print(n)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [61]:
#16 How to add a border (filled with 0's) around an existing array?
Z = np.ones((3,3))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [62]:
#17 What is the result of the following expression?

print(0 * np.nan)             # Result: nan
print(np.nan == np.nan)       # Result: False
print(np.inf > np.nan)        # Result: False
print(np.nan - np.nan)        # Result: nan
print(np.nan in set([np.nan]))# Result: True
print(0.3 == 3 * 0.1)         # Result: False

nan
False
False
nan
True
False


In [63]:
#18 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Z = np.diag(1 + np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [64]:
#19 Create an 8x8 matrix and fill it with a checkerboard pattern
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [65]:
#20 Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element

res = np.unravel_index(100, (6,7,8))
result = tuple(int(i) for i in res)
print(result)

(1, 5, 4)


In [66]:
#21 Create a checkerboard 8x8 matrix using the tile function
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [67]:
#22 Normalize a 5x5 random matrix
Z = np.random.random((5,5))
Z = (Z - Z.min()) / (Z.max() - Z.min())
Z_int = (Z * 10).astype(int)

print(Z_int)

[[ 2  5  0  9  6]
 [ 7  4  4  1  3]
 [ 0  6  3  6  2]
 [ 4  0  2 10  2]
 [ 6  6  7  6  9]]


In [68]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color_layout = [
    ("r", np.uint8),
    ("g", np.uint8), 
    ("b", np.uint8), 
    ("a", np.uint8) 
]

color = np.dtype(color_layout)

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [69]:
 #24 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
import numpy as np
A = np.ones((5, 3))
B = np.ones((3, 2))
Z = (A @ B).astype(int)

print(Z)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


In [70]:
#25 Given a 1D array, negate all elements which are between 3 and 8, in place.
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1

print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [71]:
# 26. What is the output of the following script?
# The first sum is Python's built-in sum (starts at -1)
print(sum(range(5), -1)) 

# This overwrites the built-in sum function
from numpy import *
print(sum(range(5), -1))

10
10


In [72]:
# 27. Consider an integer vector Z, which of these expressions are legal?
import numpy as np
Z = np.arange(3)

print(Z**Z)       
print(2 << Z >> 2) 
print(Z <- Z)    
print(1j*Z)      
print(Z/1/1)      


[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


In [73]:

np.seterr(all='warn')


with np.errstate(divide='ignore', invalid='ignore'):
    print("1:", np.array(0) / np.array(0))


try:
    print("2:", np.array(0) // np.array(0))
except ZeroDivisionError:
    print("2: Cannot floor divide by zero")

print("3:", np.array([np.nan]).astype(int).astype(float))

1: nan
2: 0
3: [-9.22337204e+18]


C:\Users\Malahma\AppData\Local\Temp\ipykernel_16916\2312204542.py:9: RuntimeWarning: divide by zero encountered in floor_divide
  print("2:", np.array(0) // np.array(0))
C:\Users\Malahma\AppData\Local\Temp\ipykernel_16916\2312204542.py:13: RuntimeWarning: invalid value encountered in cast
  print("3:", np.array([np.nan]).astype(int).astype(float))


In [74]:
# 28. What are the results of the following expressions?
print("1:", np.array(0) / np.array(0))
print("2:", np.array(0) // np.array(0))
print("3:", np.array([np.nan]).astype(int).astype(float))

1: nan
2: 0
3: [-9.22337204e+18]


C:\Users\Malahma\AppData\Local\Temp\ipykernel_16916\1908351598.py:2: RuntimeWarning: invalid value encountered in divide
  print("1:", np.array(0) / np.array(0))
C:\Users\Malahma\AppData\Local\Temp\ipykernel_16916\1908351598.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print("2:", np.array(0) // np.array(0))
C:\Users\Malahma\AppData\Local\Temp\ipykernel_16916\1908351598.py:4: RuntimeWarning: invalid value encountered in cast
  print("3:", np.array([np.nan]).astype(int).astype(float))


In [75]:
#29 How to round away from zero a float array 
array = np.random.uniform(-10, 10, 10)
result = np.copysign(np.ceil(np.abs(array)), array)

print(array)
print(result)

[-2.18584816 -0.02163967  1.68468036 -1.38209333 -8.34528461  2.99304685
 -0.0265567  -3.68938142 -7.84585636 -3.98665925]
[-3. -1.  2. -2. -9.  3. -1. -4. -8. -4.]


In [76]:
#30 How to find common values between two arrays? 

Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

common_values = np.intersect1d(Z1, Z2)

print(f"Array 1: {Z1}")
print(f"Array 2: {Z2}")
print(f"Common:  {common_values}")

Array 1: [4 8 3 0 3 1 7 4 5 6]
Array 2: [2 4 6 4 5 2 4 7 1 8]
Common:  [1 4 5 6 7 8]


In [77]:
#31 ow to ignore all numpy warnings (not recommended)?
old = np.seterr(all='ignore')
Z = np.ones(1) / 0
np.seterr(**old)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [78]:
import numpy as np

# #32. Is the following expression True? (★☆☆)
# np.sqrt(-1) == np.emath.sqrt(-1)

# We wrap it in a print so you see the result in the console
print("Result of np.sqrt(-1):", np.sqrt(-1))
print("Result of np.emath.sqrt(-1):", np.emath.sqrt(-1))

# This is the actual answer to the question:
comparison = np.sqrt(-1) == np.emath.sqrt(-1)
print("Is the expression True?", comparison)

Result of np.sqrt(-1): nan
Result of np.emath.sqrt(-1): 1j
Is the expression True? False


C:\Users\Malahma\AppData\Local\Temp\ipykernel_16916\1519677791.py:7: RuntimeWarning: invalid value encountered in sqrt
  print("Result of np.sqrt(-1):", np.sqrt(-1))
C:\Users\Malahma\AppData\Local\Temp\ipykernel_16916\1519677791.py:11: RuntimeWarning: invalid value encountered in sqrt
  comparison = np.sqrt(-1) == np.emath.sqrt(-1)


In [79]:
#33 How to get the dates of yesterday, today and tomorrow?

today     = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow  = today + np.timedelta64(1, 'D')

print("Yesterday: ", yesterday)
print("Today:     ", today)
print("Tomorrow:  ", tomorrow)

Yesterday:  2026-04-26
Today:      2026-04-27
Tomorrow:   2026-04-28


In [80]:
#34. How to get all the dates corresponding to the month of July 2016?
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [81]:
#35 35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3) * 1
B = np.ones(3) * 2

np.add(A, B, out=B)

np.divide(A, -2, out=A)

np.multiply(A, B, out=A)

print(A)

[-1.5 -1.5 -1.5]


In [82]:

Z = np.random.uniform(0, 10, 5)
print("Original Array:", Z)

print("Method 1 (astype):", Z.astype(int))

print("Method 2 (trunc): ", np.trunc(Z))

print("Method 3 (floor): ", np.floor(Z))

print("Method 4 (modulo):", Z - Z % 1)

Original Array: [2.98809559 3.79507753 0.09878201 4.66729818 7.37770545]
Method 1 (astype): [2 3 0 4 7]
Method 2 (trunc):  [2. 3. 0. 4. 7.]
Method 3 (floor):  [2. 3. 0. 4. 7.]
Method 4 (modulo): [2. 3. 0. 4. 7.]


In [83]:
#37 Create a 5x5 matrix with row values ranging from 0 to 4

matrix = np.zeros((5,5))
matrix += np.arange(5)

print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [84]:
#38  Consider a generator function that generates 10 integers and use it to build an array 
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(), dtype=float, count=-1)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [85]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
Z = np.linspace(0, 1, 12, endpoint=True)[1:-1]

print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [86]:
#40 Create a random vector of size 10 and sort it
Z = np.random.random(10)

Z.sort()

print(Z)

[0.03040026 0.13301276 0.4410925  0.46154865 0.46820843 0.6523527
 0.65918307 0.68028957 0.83579006 0.83839166]


In [87]:
#41  How to sum a small array faster than np.sum? 

Z = np.random.randint(0, 10, 10) 


total = np.add.reduce(Z)

print(f"Array: {Z}")
print(f"Fast Sum: {total}")

Array: [3 3 4 6 0 1 7 4 8 1]
Fast Sum: 37


In [88]:
#42 Consider two random arrays A and B, check if they are equal
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)


equal = np.array_equal(A, B)

almost_equal = np.allclose(A, B)

print(f"A: {A}")
print(f"B: {B}")
print(f"Are they exactly equal? {equal}")

A: [1 0 1 0 1]
B: [0 0 0 1 0]
Are they exactly equal? False


In [89]:
#43 Make an array immutable (read-only)

Z = np.zeros(10)

Z.flags.writeable = False

print("Array Z is now locked.")



Array Z is now locked.


In [90]:
#44 Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
import numpy as np

Z = np.random.random((10, 2))

X, Y = Z[:, 0], Z[:, 1]

R = np.sqrt(X**2 + Y**2)

T = np.arctan2(Y, X)

print("Polar Coordinates (R, Theta):")
print(np.column_stack((R, T)))

Polar Coordinates (R, Theta):
[[1.12932255 0.63734372]
 [0.56748484 1.38434335]
 [0.41441236 0.83409895]
 [1.06091989 0.93892465]
 [0.65800805 0.50529453]
 [0.69197786 0.01861297]
 [0.75764229 0.38015593]
 [0.59003356 0.18353516]
 [0.69117571 0.42869621]
 [0.31399316 0.93570759]]
