In [148]:
import numpy as np
print("NumPy is ready!")

NumPy is ready!


In [149]:
import numpy as np

print(f"NumPy Version: {np.__version__}")

np.show_config()

NumPy Version: 2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Malahma/anaconda3/Library/include
    lib directory: C:/Users/Malahma/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Malahma/anaconda3/Library/include
    lib directory: C:/Users/Malahma/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cytho

In [150]:
#create a null vector of size 10
import numpy as np
null_vector=np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [151]:
#How to find the memory size of any array
import numpy as np
array1 = np.array([1, 7, 13, 105])
print(array1)
array1.itemsize
array1.size*array1.itemsize


[  1   7  13 105]


32

In [152]:
#5 How to get the documentation of the numpy add function?
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [153]:
#6 Create a null vector of size 10 but the fifth value which is 1
import numpy as np

Z = np.zeros(10)
Z[4] = 1

print(Z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [154]:
#7 Create a vector with values ranging from 10 to 49
import numpy as np

arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [155]:
#8 Reverse a vector (first element becomes last)
import numpy as np

arr=np.arange(1,10)
arr_reversed=arr[::-1]
print(f"array {arr}")
print(f"reversed array {arr_reversed}")


array [1 2 3 4 5 6 7 8 9]
reversed array [9 8 7 6 5 4 3 2 1]


In [156]:
#9 Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
matrix=np.arange(0,9).reshape((3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [157]:
#10 Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)[0]

print(f"Indices: {indices}")

Indices: [0 1 4]


In [158]:
#11 Create a 3x3 identity matrix 
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [159]:
#12 Create a 3x3x3 array with random values
import numpy as np

array = np.random.random((3, 3, 3))
print(np.round(array, 2))

[[[0.14 0.36 0.13]
  [0.5  0.66 0.31]
  [0.81 0.08 0.98]]

 [[0.34 0.69 0.27]
  [0.36 0.28 0.11]
  [0.74 0.03 0.97]]

 [[0.03 0.11 0.44]
  [0.37 0.28 0.23]
  [0.46 0.96 0.85]]]


In [160]:
import numpy as np 

arr = np.random.randint(100, size=(10, 10))
print(arr)
print(np.min(arr))
print(np.max(arr))

[[97 69 66  4 17 55 12 46  3 77]
 [25 36 88 99 86 10 56 42 90  2]
 [99 14 10 45  7  2 61  6 51 24]
 [77 39 39 64 19 94 72 81 70  0]
 [72  3 80  4  4 66 27 62 61 24]
 [23 59 67 54 39 82 27 35 67 39]
 [48 35 53 33 96  5 90 18 15  9]
 [59  0 29 30 25 43 94 98 64 27]
 [53 58 53 44 57 63 13 15 64 68]
 [ 4  9 97 62 99 20 46 14 89 68]]
0
99


In [161]:
#14 Create a random vector of size 30 and find the mean value
Z = np.random.random(30)
m = Z.mean()

print(m)


0.5409424372863352


In [162]:
#15 Create a 2d array with 1 on the border and 0 inside 
n=np.ones((5,5))
print(n)
n[1:-1,1:-1]=0
print(n)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [163]:
#16 How to add a border (filled with 0's) around an existing array?
Z = np.ones((3,3))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#17 What is the result of the following expression?

print(0 * np.nan)             # Result: nan
print(np.nan == np.nan)       # Result: False
print(np.inf > np.nan)        # Result: False
print(np.nan - np.nan)        # Result: nan
print(np.nan in set([np.nan]))# Result: True
print(0.3 == 3 * 0.1)         # Result: False

nan
False
False
nan
True
False
