In [117]:
import numpy as np
print("NumPy is ready!")

NumPy is ready!


In [118]:
import numpy as np

print(f"NumPy Version: {np.__version__}")

np.show_config()

NumPy Version: 2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Malahma/anaconda3/Library/include
    lib directory: C:/Users/Malahma/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Malahma/anaconda3/Library/include
    lib directory: C:/Users/Malahma/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cytho

In [119]:
#create a null vector of size 10
import numpy as np
null_vector=np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
#How to find the memory size of any array
import numpy as np
array1 = np.array([1, 7, 13, 105])
print(array1)
array1.itemsize
array1.size*array1.itemsize


[  1   7  13 105]


32

In [121]:
#5 How to get the documentation of the numpy add function?
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [122]:
#6 Create a null vector of size 10 but the fifth value which is 1
import numpy as np

Z = np.zeros(10)
Z[4] = 1

print(Z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [123]:
#7 Create a vector with values ranging from 10 to 49
import numpy as np

arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [124]:
#8 Reverse a vector (first element becomes last)
import numpy as np

arr=np.arange(1,10)
arr_reversed=arr[::-1]
print(f"array {arr}")
print(f"reversed array {arr_reversed}")


array [1 2 3 4 5 6 7 8 9]
reversed array [9 8 7 6 5 4 3 2 1]


In [125]:
#9 Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
matrix=np.arange(0,9).reshape((3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [126]:
#10 Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)[0]

print(f"Indices: {indices}")

Indices: [0 1 4]


In [127]:
#11 Create a 3x3 identity matrix 
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [128]:
#12 Create a 3x3x3 array with random values
import numpy as np

array = np.random.random((3, 3, 3))
print(np.round(array, 2))

[[[0.36 0.01 0.96]
  [0.37 0.55 0.89]
  [0.24 0.52 0.32]]

 [[0.83 0.04 0.28]
  [0.59 0.14 0.94]
  [0.65 0.31 0.65]]

 [[0.34 0.8  0.14]
  [0.86 0.57 0.02]
  [0.18 0.92 0.58]]]


In [129]:
import numpy as np 

arr = np.random.randint(100, size=(10, 10))
print(arr)
print(np.min(arr))
print(np.max(arr))

[[30 81 15 87 70 21  3 92 74 75]
 [30 89 97  1 71 51 45 64 73  9]
 [90 72 30 41 32 67 43 60 54  7]
 [15 88 63 29 25 61 29  3  8 78]
 [66 96 24 12 77 98 12 21 50 74]
 [25 86 68 79 31  8 78 63 23 47]
 [83 80 98 17 79 91 85 86 12 93]
 [55 94 79 29  7 69 14 82 24 56]
 [23 45 29 99 89 81 50 99 43 49]
 [54 15 51 92 62 48 89 20 63 97]]
1
99


In [130]:
#14 Create a random vector of size 30 and find the mean value
Z = np.random.random(30)
m = Z.mean()

print(m)


0.5192276264709583


In [ ]:
#15 Create a 2d array with 1 on the border and 0 inside 
n=np.ones((5,5))
print(n)
n[1:-1,1:-1]=0
print(n)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
