In [600]:
import numpy as np
print("NumPy is ready!")

NumPy is ready!


In [601]:
import numpy as np

print(f"NumPy Version: {np.__version__}")

np.show_config()

NumPy Version: 2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Malahma/anaconda3/Library/include
    lib directory: C:/Users/Malahma/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Malahma/anaconda3/Library/include
    lib directory: C:/Users/Malahma/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cytho

In [602]:
#create a null vector of size 10
import numpy as np
null_vector=np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [603]:
#How to find the memory size of any array
import numpy as np
array1 = np.array([1, 7, 13, 105])
print(array1)
array1.itemsize
array1.size*array1.itemsize


[  1   7  13 105]


32

In [604]:
#5 How to get the documentation of the numpy add function?
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [605]:
#6 Create a null vector of size 10 but the fifth value which is 1
import numpy as np

Z = np.zeros(10)
Z[4] = 1

print(Z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [606]:
#7 Create a vector with values ranging from 10 to 49
import numpy as np

arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [607]:
#8 Reverse a vector (first element becomes last)
import numpy as np

arr=np.arange(1,10)
arr_reversed=arr[::-1]
print(f"array {arr}")
print(f"reversed array {arr_reversed}")


array [1 2 3 4 5 6 7 8 9]
reversed array [9 8 7 6 5 4 3 2 1]


In [608]:
#9 Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
matrix=np.arange(0,9).reshape((3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [609]:
#10 Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)[0]

print(f"Indices: {indices}")

Indices: [0 1 4]


In [610]:
#11 Create a 3x3 identity matrix 
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [611]:
#12 Create a 3x3x3 array with random values
import numpy as np

array = np.random.random((3, 3, 3))
print(np.round(array, 2))

[[[0.59 0.72 0.96]
  [0.58 0.17 0.16]
  [0.23 0.36 0.14]]

 [[0.14 0.36 0.5 ]
  [0.51 0.53 0.8 ]
  [0.13 0.3  0.14]]

 [[0.03 0.97 0.55]
  [0.07 0.11 0.68]
  [0.45 0.11 0.26]]]


In [612]:
import numpy as np 

arr = np.random.randint(100, size=(10, 10))
print(arr)
print(np.min(arr))
print(np.max(arr))

[[40 15 89 33 84 57 15 41 39 18]
 [32 14 29 77 13 65 92 63 76 87]
 [19  0 86 68 74 82 30 85 82 49]
 [24 32 53 44 83 85 27 68 34 94]
 [44 72 62 53 66 40 62 31 77 36]
 [51 36 79 72 75 40 87 85 28 68]
 [61 16 61 28 46 10 90 77  1 57]
 [33 43 97 86 49 16 74 47 60 70]
 [79 26 93 73 29 34 49 27 31 95]
 [25 57 11 85 10 25 81  7 81 50]]
0
97


In [613]:
#14 Create a random vector of size 30 and find the mean value
Z = np.random.random(30)
m = Z.mean()

print(m)


0.4369757190587889


In [614]:
#15 Create a 2d array with 1 on the border and 0 inside 
n=np.ones((5,5))
print(n)
n[1:-1,1:-1]=0
print(n)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [615]:
#16 How to add a border (filled with 0's) around an existing array?
Z = np.ones((3,3))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [616]:
#17 What is the result of the following expression?

print(0 * np.nan)             # Result: nan
print(np.nan == np.nan)       # Result: False
print(np.inf > np.nan)        # Result: False
print(np.nan - np.nan)        # Result: nan
print(np.nan in set([np.nan]))# Result: True
print(0.3 == 3 * 0.1)         # Result: False

nan
False
False
nan
True
False


In [617]:
#18 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Z = np.diag(1 + np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [618]:
#19 Create an 8x8 matrix and fill it with a checkerboard pattern
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [619]:
#20 Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element

res = np.unravel_index(100, (6,7,8))
result = tuple(int(i) for i in res)
print(result)

(1, 5, 4)


In [620]:
#21 Create a checkerboard 8x8 matrix using the tile function
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [621]:
#22 Normalize a 5x5 random matrix
Z = np.random.random((5,5))
Z = (Z - Z.min()) / (Z.max() - Z.min())
Z_int = (Z * 10).astype(int)

print(Z_int)

[[ 5  7  9  6  4]
 [ 7  0  5  6  3]
 [ 3  0  2  0  1]
 [ 4  5  7  4  3]
 [10  2  9  0  0]]


In [622]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color_layout = [
    ("r", np.uint8),
    ("g", np.uint8), 
    ("b", np.uint8), 
    ("a", np.uint8) 
]

color = np.dtype(color_layout)

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [623]:
 #24 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
import numpy as np
A = np.ones((5, 3))
B = np.ones((3, 2))
Z = (A @ B).astype(int)

print(Z)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


In [624]:
#25 Given a 1D array, negate all elements which are between 3 and 8, in place.
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1

print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [625]:
# 26. What is the output of the following script?
# The first sum is Python's built-in sum (starts at -1)
print(sum(range(5), -1)) 

# This overwrites the built-in sum function
from numpy import *
print(sum(range(5), -1))

10
10


In [626]:
# 27. Consider an integer vector Z, which of these expressions are legal?
import numpy as np
Z = np.arange(3)

print(Z**Z)       
print(2 << Z >> 2) 
print(Z <- Z)    
print(1j*Z)      
print(Z/1/1)      


[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


In [627]:
# 28. What are the results of the following expressions?
print("1:", np.array(0) / np.array(0))
print("2:", np.array(0) // np.array(0))
print("3:", np.array([np.nan]).astype(int).astype(float))

NameError: log specified for invalid value (in divide) but no object with write method found.

In [ ]:
#29 How to round away from zero a float array 
array = np.random.uniform(-10, 10, 10)
result = np.copysign(np.ceil(np.abs(array)), array)

print(array)
print(result)

[ 4.89380244 -6.56385858  3.17665435 -2.56125712  2.45584528 -8.70811445
  7.39950938  2.66577029 -8.87091597  3.75286052]
[ 5. -7.  4. -3.  3. -9.  8.  3. -9.  4.]


In [ ]:
#30 How to find common values between two arrays? 

Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

common_values = np.intersect1d(Z1, Z2)

print(f"Array 1: {Z1}")
print(f"Array 2: {Z2}")
print(f"Common:  {common_values}")

Array 1: [5 8 0 0 9 5 0 1 2 3]
Array 2: [4 6 7 9 6 0 2 1 3 7]
Common:  [0 1 2 3 9]


In [ ]:
#31 ow to ignore all numpy warnings (not recommended)?
old = np.seterr(all='ignore')
Z = np.ones(1) / 0
np.seterr(**old)

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}